#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
source "$PROJECT_ROOT/versions.env"

log() { printf '\n[bootstrap] %s\n' "$*"; }
fail() { printf '\n[bootstrap] ERROR: %s\n' "$*" >&2; exit 1; }

case "$(uname -s)" in
  Linux) ;;
  *) fail "This sandbox bootstrap currently supports Linux only." ;;
esac

case "$(uname -m)" in
  x86_64|amd64) ;;
  *) fail "Pinned Android command-line tools package is for Linux x86_64." ;;
esac

for tool in java curl unzip sha256sum; do
  command -v "$tool" >/dev/null 2>&1 || fail "Required host tool not found: $tool"
done

JAVA_MAJOR="$(java -version 2>&1 | awk -F'[\".]' '/version/ {print $2; exit}')"
[[ "$JAVA_MAJOR" =~ ^[0-9]+$ ]] || fail "Cannot determine Java version."
(( JAVA_MAJOR >= 17 )) || fail "JDK 17+ is required; found Java $JAVA_MAJOR."

SDK_ROOT="${ANDROID_SDK_ROOT:-${ANDROID_HOME:-$HOME/.android-sdk}}"
CACHE_ROOT="${XDG_CACHE_HOME:-$HOME/.cache}/videomosaic-bootstrap"
TOOLS_DIR="$SDK_ROOT/cmdline-tools/$ANDROID_CMDLINE_TOOLS_BUILD"
SDKMANAGER="$TOOLS_DIR/bin/sdkmanager"
mkdir -p "$SDK_ROOT/cmdline-tools" "$CACHE_ROOT"

if [[ ! -x "$SDKMANAGER" ]]; then
  ARCHIVE="$CACHE_ROOT/commandlinetools-linux-${ANDROID_CMDLINE_TOOLS_BUILD}.zip"
  if [[ ! -f "$ARCHIVE" ]]; then
    log "Downloading pinned Android command-line tools (${ANDROID_CMDLINE_TOOLS_BUILD})"
    curl --fail --location --retry 4 --retry-delay 2 \
      "$ANDROID_CMDLINE_TOOLS_URL" -o "$ARCHIVE"
  else
    log "Using cached Android command-line tools archive"
  fi

  printf '%s  %s\n' "$ANDROID_CMDLINE_TOOLS_SHA256" "$ARCHIVE" | sha256sum --check - >/dev/null \
    || { rm -f "$ARCHIVE"; fail "Android command-line tools checksum mismatch."; }

  TMP_DIR="$(mktemp -d)"
  trap 'rm -rf "$TMP_DIR"' EXIT
  unzip -q "$ARCHIVE" -d "$TMP_DIR"
  rm -rf "$TOOLS_DIR"
  mkdir -p "$TOOLS_DIR"
  cp -a "$TMP_DIR/cmdline-tools/." "$TOOLS_DIR/"
  rm -rf "$TMP_DIR"
  trap - EXIT
else
  log "Android command-line tools already installed"
fi

rm -rf "$SDK_ROOT/cmdline-tools/latest"
ln -s "$ANDROID_CMDLINE_TOOLS_BUILD" "$SDK_ROOT/cmdline-tools/latest"
SDKMANAGER="$SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"

export ANDROID_SDK_ROOT="$SDK_ROOT"
export ANDROID_HOME="$SDK_ROOT"
export PATH="$SDK_ROOT/platform-tools:$SDK_ROOT/cmdline-tools/latest/bin:$PATH"

log "Accepting Android SDK licenses"
yes | "$SDKMANAGER" --sdk_root="$SDK_ROOT" --licenses >/dev/null 2>&1 || true

PACKAGES=(
  "platform-tools"
  "platforms;android-${ANDROID_COMPILE_SDK}"
  "build-tools;${ANDROID_BUILD_TOOLS}"
)

log "Installing/verifying SDK packages: ${PACKAGES[*]}"
"$SDKMANAGER" --sdk_root="$SDK_ROOT" "${PACKAGES[@]}"

cat > "$PROJECT_ROOT/local.properties" <<LOCAL_EOF
# Generated by scripts/bootstrap_android.sh; do not commit.
sdk.dir=$SDK_ROOT
LOCAL_EOF

log "Android SDK ready at $SDK_ROOT"
bash "$SCRIPT_DIR/ensure_gradle_wrapper.sh"

log "Running environment checks"
bash "$SCRIPT_DIR/check_environment.sh"

printf '\n[bootstrap] Done. Build with: ./gradlew :app:assembleDebug\n'
